sonar.projectKey=discover-adblock
sonar.sources=app/src/main,app/src/debug
sonar.tests=app/src/test,app/src/androidTest

sonar.exclusions=app/src/main/kotlin/eu/hxreborn/discoveradsfilter/ui/util/Scrollbar.kt,tools/**
